spring:
  profiles:
    active: server
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    #    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
---

spring:
  config:
    activate:
      on-profile: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}